### ISSUE TITLE
selectInput (without selectize) - Single - UI looks off on Safari

### ISSUE THREAD

**Issue by MadhulikaTanuboddi** [rstudio/bootstraplib#119]
Run the following shiny app and open the app in Safari

```
library(shiny)
library(bootstraplib)
shinyOptions(bootstraplib = TRUE)

bs_theme_new()
bs_theme_base_colors(bg = "#002B36", fg = "#EEE8D5")
bs_theme_accent_colors(primary = "#2AA198")

ui <- fluidPage(
  tags$h4("With selectize"),
  selectInput("single", "Choose single", choices = state.abb),
  selectInput("multiple", "Choose multiple", choices = state.abb, multiple = TRUE),
  tags$h4("Without selectize"),
  selectInput("single2", "Choose single", choices = state.abb, selectize = FALSE),
  selectInput("multiple2", "Choose multiple", choices = state.abb, multiple = TRUE, selectize = FALSE),
)

shinyApp(ui, function(input, output) {})
```

Notice the selectInput option without selectize. The Input box has a grey shady background which does not seem right. Applicable to both bs(3) and bs(4+3).

<img width="1225" alt="safari_without_selectize_input_single_option_UI" src="https://user-images.githubusercontent.com/5369655/94705851-5f5be380-02f6-11eb-837b-fc215af6fb16.png">

<img width="481" alt="Safari_without_selectize_select_box" src="https://user-images.githubusercontent.com/5369655/94710131-54f01880-02fb-11eb-86b2-004f3d939d5b.png">

**Comment by MadhulikaTanuboddi** [comment]
Related to https://github.com/rstudio/shiny/pull/2958

**Comment by cpsievert** [comment]
I think we can ignore this issue, at least for now --- this a result of how safari's default rendering of `<select>` (via `-webkit-appearance: menulist`). I don't know for sure, but Bootstrap probably doesn't provide a different default for a good reason.

Also, folks who use `selectInput()` over `selectizeInput()` are likely doing it because they want more control over the HTML/CSS anyway, so I don't think this is something worth worrying about
